server:
  port: 8001
spring:
  cloud:
      config:
        server:
          git:
            default-label: eureka
            uri: https://github.com/EliasVGZ/Microservicios
            search-paths: config-data
  application:
    name: config-service